In [22]:
import numpy as np
import pandas as pd
from datetime import datetime, time

df = pd.DataFrame(np.random.randint(0,100,size=(100, 5)), columns=list('Ar''D''C''D'))

In [199]:
list_featuresHSI = []
for h in range(0, 6):
    for m in range(0, 60):

        t = time(h, m)
        time_convert = t.strftime("%H:%M")

        list_featuresHSI.append("HSI_"+str(time_convert))
        if(h == 5 ): break
            

df_HSI_UTCminus5 = pd.DataFrame(np.array([range(len(list_featuresHSI))]), columns=list_featuresHSI)
df_HSI_UTCminus5.head(2)

HSI_00:00  HSI_00:01  HSI_00:02  HSI_00:03  HSI_00:04  HSI_00:05  \
0          0          1          2          3          4          5   

   HSI_00:06  HSI_00:07  HSI_00:08  HSI_00:09  ...  HSI_04:51  HSI_04:52  \
0          6          7          8          9  ...        291        292   

   HSI_04:53  HSI_04:54  HSI_04:55  HSI_04:56  HSI_04:57  HSI_04:58  \
0        293        294        295        296        297        298   

   HSI_04:59  HSI_05:00  
0        299        300  

[1 rows x 301 columns]

In [97]:
list_featuresDAX = []
list_featuresDAX.append("DAX_close_preday_14:00")
for h in range(2, 6):
    for m in range(0, 60):

        t = time(h, m)
        time_convert = t.strftime("%H:%M")

        list_featuresDAX.append("DAX_"+str(time_convert))
        if(h == 5): break
            
df_DAX_UTCminus5 = pd.DataFrame(np.array([range(len(list_featuresDAX))]), columns=list_featuresDAX)
df_DAX_UTCminus5.head(2)

DAX_close_preday_14:00  DAX_02:00  DAX_02:01  DAX_02:02  DAX_02:03  \
0                       0          1          2          3          4   

   DAX_02:04  DAX_02:05  DAX_02:06  DAX_02:07  DAX_02:08  ...  DAX_04:51  \
0          5          6          7          8          9  ...        172   

   DAX_04:52  DAX_04:53  DAX_04:54  DAX_04:55  DAX_04:56  DAX_04:57  \
0        173        174        175        176        177        178   

   DAX_04:58  DAX_04:59  DAX_05:00  
0        179        180        181  

[1 rows x 182 columns]

In [74]:
df_DAX_UTCminus5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 182 entries, DAX_close_preday_14:00 to DAX_05:00
dtypes: int32(182)
memory usage: 856.0 bytes


In [94]:
np.array([range(len(list_featuresDAX))])

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [93]:
np.random.randint(0,100,size=(1,len(list_featuresDAX)))

array([[44, 67, 97, 38, 33, 58, 96, 22,  9,  4, 88, 70, 26, 18, 64, 76,
        47, 65, 52, 95, 17, 14, 15, 83, 22, 87, 94, 18, 32, 63, 63,  6,
        24, 10, 93, 24, 19, 98, 11, 95, 87, 66, 50, 60, 70,  5, 59,  2,
        37,  7, 27, 89,  7, 85, 34, 54, 64, 38, 45, 62, 99, 40, 24, 88,
        30, 21, 21, 74,  0, 98, 61, 33,  1, 12,  6, 13, 96, 44, 64, 12,
        47,  5, 20, 68, 21, 90, 62,  7, 11, 21, 79, 98, 87, 34,  0, 31,
        19, 63,  0, 34, 68, 73, 80, 87, 78, 97, 86, 48, 38, 15, 29, 17,
        26, 45,  6, 68,  2, 29, 74, 77, 24, 26, 30, 44, 11, 36,  0, 37,
        68, 43, 78, 41, 21, 81, 85, 14,  4, 23, 32, 65, 86, 69, 91, 55,
        42, 95, 85, 48, 80, 90, 45, 18, 32, 62, 38, 67,  1, 97,  6, 56,
         2, 48, 64, 13,  9, 20, 86, 10, 17, 65, 89, 77, 39, 47, 94,  0,
        51,  5, 10, 21, 50, 91]])

In [100]:
pd.concat([df_HSI_UTCminus5,df_DAX_UTCminus5],axis=1)

HSI_00:00  HSI_00:01  HSI_00:02  HSI_00:03  HSI_00:04  HSI_00:05  \
0          0          1          2          3          4          5   

   HSI_00:06  HSI_00:07  HSI_00:08  HSI_00:09  ...  DAX_04:51  DAX_04:52  \
0          6          7          8          9  ...        172        173   

   DAX_04:53  DAX_04:54  DAX_04:55  DAX_04:56  DAX_04:57  DAX_04:58  \
0        174        175        176        177        178        179   

   DAX_04:59  DAX_05:00  
0        180        181  

[1 rows x 363 columns]

In [155]:
list=[1,2,3]
np.array([range(len(list)),range(0,len(list))])

array([[0, 1, 2],
       [0, 1, 2]])

In [438]:
x = np.array([['2019-01-10']], dtype=np.datetime64)
array_date = np.repeat(x, 256, axis = 0)


In [314]:


time = pd.timedelta_range(0, periods=301, freq="T")
array_time = time.to_array + np.arange(301)

array_time
#df['end_time_times'] = pd.to_datetime(df['end_time']).dt.time

AttributeError: 'TimedeltaIndex' object has no attribute 'to_array'

In [310]:
close = np.arange(301)
close.reshape(301)
print(close.shape)
close

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [302]:
dataframe = np.concatenate((date,close), axis = 0)
dataframe

ValueError: zero-dimensional arrays cannot be concatenated

In [317]:
from datetime import datetime, time
list_featuresHSI = []
for h in range(0, 4):
    for m in range(0, 60):

        t = time(h, m)
        time_convert = t.strftime("%H:%M")

        list_featuresHSI.append(str(time_convert))
        if (h == 3 and m >= 29): break
for h in range(4, 5):
    for m in range(15, 60):

        t = time(h, m)
        time_convert = t.strftime("%H:%M")

        list_featuresHSI.append(str(time_convert))
        if (h == 5): break

hsiClose = time(5, 0).strftime("%H:%M")
list_featuresHSI.append(str(hsiClose))


len(list_featuresHSI)

256

In [440]:
array_time =  np.asarray([list_featuresHSI])
array_time.reshape(256,1)
array_time.size
array_time

array([['00:00', '00:01', '00:02', '00:03', '00:04', '00:05', '00:06',
        '00:07', '00:08', '00:09', '00:10', '00:11', '00:12', '00:13',
        '00:14', '00:15', '00:16', '00:17', '00:18', '00:19', '00:20',
        '00:21', '00:22', '00:23', '00:24', '00:25', '00:26', '00:27',
        '00:28', '00:29', '00:30', '00:31', '00:32', '00:33', '00:34',
        '00:35', '00:36', '00:37', '00:38', '00:39', '00:40', '00:41',
        '00:42', '00:43', '00:44', '00:45', '00:46', '00:47', '00:48',
        '00:49', '00:50', '00:51', '00:52', '00:53', '00:54', '00:55',
        '00:56', '00:57', '00:58', '00:59', '01:00', '01:01', '01:02',
        '01:03', '01:04', '01:05', '01:06', '01:07', '01:08', '01:09',
        '01:10', '01:11', '01:12', '01:13', '01:14', '01:15', '01:16',
        '01:17', '01:18', '01:19', '01:20', '01:21', '01:22', '01:23',
        '01:24', '01:25', '01:26', '01:27', '01:28', '01:29', '01:30',
        '01:31', '01:32', '01:33', '01:34', '01:35', '01:36', '01:37',
      

In [334]:
new = np.concatenate((array_date,array_time), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [331]:
print(array_date.size)
print(array_time.size)

256
256


In [352]:
list_featuresHSI
array_featuresHSI = np.array(list_featuresHSI)
array_featuresHSI.resize(256,1)

In [441]:
df_time = pd.DataFrame(list_featuresHSI, columns = ['time'])
df_close = pd.DataFrame(np.transpose(np.array([range(len(list_featuresHSI))])), columns = ['close'])
df_date = pd.DataFrame(array_date, columns = ['date'])


In [442]:
result = pd.concat([df_date,df_time, df_close], axis=1, sort=False)

In [443]:
result

date   time  close
0   2019-01-10  00:00      0
1   2019-01-10  00:01      1
2   2019-01-10  00:02      2
3   2019-01-10  00:03      3
4   2019-01-10  00:04      4
5   2019-01-10  00:05      5
6   2019-01-10  00:06      6
7   2019-01-10  00:07      7
8   2019-01-10  00:08      8
9   2019-01-10  00:09      9
10  2019-01-10  00:10     10
11  2019-01-10  00:11     11
12  2019-01-10  00:12     12
13  2019-01-10  00:13     13
14  2019-01-10  00:14     14
15  2019-01-10  00:15     15
16  2019-01-10  00:16     16
17  2019-01-10  00:17     17
18  2019-01-10  00:18     18
19  2019-01-10  00:19     19
20  2019-01-10  00:20     20
21  2019-01-10  00:21     21
22  2019-01-10  00:22     22
23  2019-01-10  00:23     23
24  2019-01-10  00:24     24
25  2019-01-10  00:25     25
26  2019-01-10  00:26     26
27  2019-01-10  00:27     27
28  2019-01-10  00:28     28
29  2019-01-10  00:29     29
30  2019-01-10  00:30     30
31  2019-01-10  00:31     31
32  2019-01-10  00:32     32
33  2019-01-10  00:33     33
34  2019-01-10  00:34     34
35  2019-01-10  00:35     35
36  2019-01-10  00:36     36
37  2019-01-10  00:37     37
38  2019-01-10  00:38     38
39  2019-01-10  00:39     39
40  2019-01-10  00:40     40
41  2019-01-10  00:41     41
42  2019-01-10  00:42     42
43  2019-01-10  00:43     43
44  2019-01-10  00:44     44
45  2019-01-10  00:45     45
46  2019-01-10  00:46     46
47  2019-01-10  00:47     47
48  2019-01-10  00:48     48
49  2019-01-10  00:49     49
50  2019-01-10  00:50     50
51  2019-01-10  00:51     51
52  2019-01-10  00:52     52
53  2019-01-10  00:53     53
54  2019-01-10  00:54     54
55  2019-01-10  00:55     55
56  2019-01-10  00:56     56
57  2019-01-10  00:57     57
58  2019-01-10  00:58     58
59  2019-01-10  00:59     59
60  2019-01-10  01:00     60
61  2019-01-10  01:01     61
62  2019-01-10  01:02     62
63  2019-01-10  01:03     63
64  2019-01-10  01:04     64
65  2019-01-10  01:05     65
66  2019-01-10  01:06     66
67  2019-01-10  01:07     67
68  2019-01-10  01:08     68
69  2019-01-10  01:09     69
70  2019-01-10  01:10     70
71  2019-01-10  01:11     71
72  2019-01-10  01:12     72
73  2019-01-10  01:13     73
74  2019-01-10  01:14     74
75  2019-01-10  01:15     75
76  2019-01-10  01:16     76
77  2019-01-10  01:17     77
78  2019-01-10  01:18     78
79  2019-01-10  01:19     79
80  2019-01-10  01:20     80
81  2019-01-10  01:21     81
82  2019-01-10  01:22     82
83  2019-01-10  01:23     83
84  2019-01-10  01:24     84
85  2019-01-10  01:25     85
86  2019-01-10  01:26     86
87  2019-01-10  01:27     87
88  2019-01-10  01:28     88
89  2019-01-10  01:29     89
90  2019-01-10  01:30     90
91  2019-01-10  01:31     91
92  2019-01-10  01:32     92
93  2019-01-10  01:33     93
94  2019-01-10  01:34     94
95  2019-01-10  01:35     95
96  2019-01-10  01:36     96
97  2019-01-10  01:37     97
98  2019-01-10  01:38     98
99  2019-01-10  01:39     99
100 2019-01-10  01:40    100
101 2019-01-10  01:41    101
102 2019-01-10  01:42    102
103 2019-01-10  01:43    103
104 2019-01-10  01:44    104
105 2019-01-10  01:45    105
106 2019-01-10  01:46    106
107 2019-01-10  01:47    107
108 2019-01-10  01:48    108
109 2019-01-10  01:49    109
110 2019-01-10  01:50    110
111 2019-01-10  01:51    111
112 2019-01-10  01:52    112
113 2019-01-10  01:53    113
114 2019-01-10  01:54    114
115 2019-01-10  01:55    115
116 2019-01-10  01:56    116
117 2019-01-10  01:57    117
118 2019-01-10  01:58    118
119 2019-01-10  01:59    119
120 2019-01-10  02:00    120
121 2019-01-10  02:01    121
122 2019-01-10  02:02    122
123 2019-01-10  02:03    123
124 2019-01-10  02:04    124
125 2019-01-10  02:05    125
126 2019-01-10  02:06    126
127 2019-01-10  02:07    127
128 2019-01-10  02:08    128
129 2019-01-10  02:09    129
130 2019-01-10  02:10    130
131 2019-01-10  02:11    131
132 2019-01-10  02:12    132
133 2019-01-10  02:13    133
134 2019-01-10  02:14    134
135 2019-01-10  02:15    135
136 2019-01-10  02:16    136
137 2019

In [456]:
ist = pd.read_csv('D:\ISTDATAFRAME.csv')
soll = pd.read_csv('D:\SOLLDATAFRAME.csv')

In [463]:
ist.head()
ist.info

<bound method DataFrame.info of    Unnamed: 0  HSI_00:00  HSI_00:01  HSI_00:02  HSI_00:03  HSI_00:04  \
0           0          0          1          2          3          4   

   HSI_00:05  HSI_00:06  HSI_00:07  HSI_00:08  HSI_00:09  HSI_00:10  \
0          5          6          7          8          9         10   

   HSI_00:11  HSI_00:12  HSI_00:13  HSI_00:14  HSI_00:15  HSI_00:16  \
0         11         12         13         14         15         16   

   HSI_00:17  HSI_00:18  HSI_00:19  HSI_00:20  HSI_00:21  HSI_00:22  \
0         17         18         19         20         21         22   

   HSI_00:23  HSI_00:24  HSI_00:25  HSI_00:26  HSI_00:27  HSI_00:28  \
0         23         24         25         26         27         28   

   HSI_00:29  HSI_00:30  HSI_00:31  HSI_00:32  HSI_00:33  HSI_00:34  \
0         29         30         31         32         33         34   

   HSI_00:35  HSI_00:36  HSI_00:37  HSI_00:38  HSI_00:39  HSI_00:40  \
0         35         36         37   

In [462]:
soll.head()
soll.info

<bound method DataFrame.info of    Unnamed: 0  HSI_00:00  HSI_00:01  HSI_00:02  HSI_00:03  HSI_00:04  \
0           0          0          1          2          3          4   

   HSI_00:05  HSI_00:06  HSI_00:07  HSI_00:08  HSI_00:09  HSI_00:10  \
0          5          6          7          8          9         10   

   HSI_00:11  HSI_00:12  HSI_00:13  HSI_00:14  HSI_00:15  HSI_00:16  \
0         11         12         13         14         15         16   

   HSI_00:17  HSI_00:18  HSI_00:19  HSI_00:20  HSI_00:21  HSI_00:22  \
0         17         18         19         20         21         22   

   HSI_00:23  HSI_00:24  HSI_00:25  HSI_00:26  HSI_00:27  HSI_00:28  \
0         23         24         25         26         27         28   

   HSI_00:29  HSI_00:30  HSI_00:31  HSI_00:32  HSI_00:33  HSI_00:34  \
0         29         30         31         32         33         34   

   HSI_00:35  HSI_00:36  HSI_00:37  HSI_00:38  HSI_00:39  HSI_00:40  \
0         35         36         37   